### ISSUE TITLE
Snow canvas breaks design

### ISSUE THREAD

**Issue by matiasanaya** [gastonfariasb/patagoniclabs-web#3]
El canvas no toma full-width cuando:
- Haces un window resize en desktop.
- Cargas la pagina en tablet y la giras.

![Screen Shot 2013-02-21 at 4 34 21 PM](https://f.cloud.github.com/assets/1661017/181893/c933203e-7c5d-11e2-85f8-28c2dace2ab2.png)
![Screen Shot 2013-02-21 at 4 34 37 PM](https://f.cloud.github.com/assets/1661017/181894/c956714c-7c5d-11e2-8491-b544493ec61a.png)

**Comment by gastonfariasb** [comment]
SI ES QUE LO HACE EL SIZE... AL CAGRAR. 

NO LO CAMBIARIA PRO EL MOMENTO
